- hosts: all
  become: true
  tasks:
  - name: Install docker-compose
    apt:
      name: docker-compose
      state: present
      update_cache: true
  - name: set vm.max_map_count
    sysctl:
      name: vm.max_map_count
      value: '262144'
      sysctl_set: true
      reload: true
  - name: Create directory
    file:
      path: /var/zabbix
      state: directory
  - name: Copy docker-compose
    copy:
      src: docker-compose.yml
      dest: /var/zabbix/docker-compose.yml
  - name: Run
    docker_compose:
      project_src: /var/zabbix/


